/* eslint-disable */

// @ts-nocheck 

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CoursesCurriculumRouteImport } from './routes/courses.curriculum'
import { Route as CoursesNewRouteImport } from './routes/courses.new'
import { Route as DiscountsIndexRouteImport } from './routes/discounts.index'
import { Route as DiscountsDiscountIdRouteImport } from './routes/discounts_.$discountId'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as ManageActivityRouteImport } from './routes/manage.activity'
import { Route as ManageBotLogsRouteImport } from './routes/manage.bot-logs'
import { Route as ManageFaqsRouteImport } from './routes/manage.faqs'
import { Route as PaymentVerifyRouteImport } from './routes/payment.verify'
import { Route as SettingsOrganizationRouteImport } from './routes/settings.organization'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as ApplicationsApplicationIdEditRouteImport } from './routes/applications.$applicationId.edit'
import { Route as ManageCoursesIndexRouteImport } from './routes/manage.courses.index'
import { Route as ManageDiscountsIndexRouteImport } from './routes/manage.discounts.index'
import { Route as ManageDiscountsDiscountIdRouteImport } from './routes/manage.discounts.$discountId'
import { Route as ManageDiscountsNewRouteImport } from './routes/manage.discounts.new'
import { Route as ManageEventsIndexRouteImport } from './routes/manage.events.index'
import { Route as ManageJobsIndexRouteImport } from './routes/manage.jobs.index'
import { Route as UsersUserIdEditRouteImport } from './routes/users_.$userId.edit'
import { Route as ManageCoursesCourseIdEditRouteImport } from './routes/manage.courses.$courseId.edit'
import { Route as ManageCoursesCourseIdLessonsRouteImport } from './routes/manage.courses.$courseId.lessons'
import { Route as ManageDiscountsDiscountIdEditRouteImport } from './routes/manage.discounts_.$discountId.edit'
import { Route as ManageEventsEventIdAttendeesRouteImport } from './routes/manage.events.$eventId.attendees'
import { Route as ManageEventsEventIdEditRouteImport } from './routes/manage.events.$eventId.edit'
import { Route as ManageJobsJobIdApplicantsRouteImport } from './routes/manage.jobs.$jobId.applicants'
import { Route as ManageJobsJobIdEditRouteImport } from './routes/manage.jobs.$jobId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCurriculumRoute = CoursesCurriculumRouteImport.update({
  id: '/courses/curriculum',
  path: '/courses/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesNewRoute = CoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsIndexRoute = DiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsDiscountIdRoute = DiscountsDiscountIdRouteImport.update({
  id: '/discounts_/$discountId',
  path: '/discounts/$discountId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageActivityRoute = ManageActivityRouteImport.update({
  id: '/manage/activity',
  path: '/manage/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBotLogsRoute = ManageBotLogsRouteImport.update({
  id: '/manage/bot-logs',
  path: '/manage/bot-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageFaqsRoute = ManageFaqsRouteImport.update({
  id: '/manage/faqs',
  path: '/manage/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentVerifyRoute = PaymentVerifyRouteImport.update({
  id: '/payment/verify',
  path: '/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdEditRoute =
  ApplicationsApplicationIdEditRouteImport.update({
    id: '/applications/$applicationId/edit',
    path: '/applications/$applicationId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageCoursesIndexRoute = ManageCoursesIndexRouteImport.update({
  id: '/manage/courses/',
  path: '/manage/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDiscountsIndexRoute = ManageDiscountsIndexRouteImport.update({
  id: '/manage/discounts/',
  path: '/manage/discounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDiscountsDiscountIdRoute =
  ManageDiscountsDiscountIdRouteImport.update({
    id: '/manage/discounts/$discountId',
    path: '/manage/discounts/$discountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageDiscountsNewRoute = ManageDiscountsNewRouteImport.update({
  id: '/manage/discounts/new',
  path: '/manage/discounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageEventsIndexRoute = ManageEventsIndexRouteImport.update({
  id: '/manage/events/',
  path: '/manage/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageJobsIndexRoute = ManageJobsIndexRouteImport.update({
  id: '/manage/jobs/',
  path: '/manage/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/users_/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCoursesCourseIdEditRoute =
  ManageCoursesCourseIdEditRouteImport.update({
    id: '/manage/courses/$courseId/edit',
    path: '/manage/courses/$courseId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageCoursesCourseIdLessonsRoute =
  ManageCoursesCourseIdLessonsRouteImport.update({
    id: '/manage/courses/$courseId/lessons',
    path: '/manage/courses/$courseId/lessons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageDiscountsDiscountIdEditRoute =
  ManageDiscountsDiscountIdEditRouteImport.update({
    id: '/manage/discounts_/$discountId/edit',
    path: '/manage/discounts/$discountId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageEventsEventIdAttendeesRoute =
  ManageEventsEventIdAttendeesRouteImport.update({
    id: '/manage/events/$eventId/attendees',
    path: '/manage/events/$eventId/attendees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageEventsEventIdEditRoute = ManageEventsEventIdEditRouteImport.update({
  id: '/manage/events/$eventId/edit',
  path: '/manage/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageJobsJobIdApplicantsRoute =
  ManageJobsJobIdApplicantsRouteImport.update({
    id: '/manage/jobs/$jobId/applicants',
    path: '/manage/jobs/$jobId/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageJobsJobIdEditRoute = ManageJobsJobIdEditRouteImport.update({
  id: '/manage/jobs/$jobId/edit',
  path: '/manage/jobs/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/landing': typeof LandingRoute
  '/learn': typeof LearnRoute
  '/my-learning': typeof MyLearningRoute
  '/organization': typeof OrganizationRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/curriculum': typeof CoursesCurriculumRoute
  '/courses/new': typeof CoursesNewRoute
  '/discounts/$discountId': typeof DiscountsDiscountIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/manage/activity': typeof ManageActivityRoute
  '/manage/bot-logs': typeof ManageBotLogsRoute
  '/manage/faqs': typeof ManageFaqsRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/discounts/': typeof DiscountsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/applications/$applicationId/edit': typeof ApplicationsApplicationIdEditRoute
  '/manage/discounts/$discountId': typeof ManageDiscountsDiscountIdRoute
  '/manage/discounts/new': typeof ManageDiscountsNewRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/manage/courses/': typeof ManageCoursesIndexRoute
  '/manage/discounts/': typeof ManageDiscountsIndexRoute
  '/manage/events/': typeof ManageEventsIndexRoute
  '/manage/jobs/': typeof ManageJobsIndexRoute
  '/manage/courses/$courseId/edit': typeof ManageCoursesCourseIdEditRoute
  '/manage/courses/$courseId/lessons': typeof ManageCoursesCourseIdLessonsRoute
  '/manage/discounts/$discountId/edit': typeof ManageDiscountsDiscountIdEditRoute
  '/manage/events/$eventId/attendees': typeof ManageEventsEventIdAttendeesRoute
  '/manage/events/$eventId/edit': typeof ManageEventsEventIdEditRoute
  '/manage/jobs/$jobId/applicants': typeof ManageJobsJobIdApplicantsRoute
  '/manage/jobs/$jobId/edit': typeof ManageJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/landing': typeof LandingRoute
  '/learn': typeof LearnRoute
  '/my-learning': typeof MyLearningRoute
  '/organization': typeof OrganizationRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/curriculum': typeof CoursesCurriculumRoute
  '/courses/new': typeof CoursesNewRoute
  '/discounts/$discountId': typeof DiscountsDiscountIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/manage/activity': typeof ManageActivityRoute
  '/manage/bot-logs': typeof ManageBotLogsRoute
  '/manage/faqs': typeof ManageFaqsRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/applications': typeof ApplicationsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/discounts': typeof DiscountsIndexRoute
  '/events': typeof EventsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/users': typeof UsersIndexRoute
  '/applications/$applicationId/edit': typeof ApplicationsApplicationIdEditRoute
  '/manage/discounts/$discountId': typeof ManageDiscountsDiscountIdRoute
  '/manage/discounts/new': typeof ManageDiscountsNewRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/manage/courses': typeof ManageCoursesIndexRoute
  '/manage/discounts': typeof ManageDiscountsIndexRoute
  '/manage/events': typeof ManageEventsIndexRoute
  '/manage/jobs': typeof ManageJobsIndexRoute
  '/manage/courses/$courseId/edit': typeof ManageCoursesCourseIdEditRoute
  '/manage/courses/$courseId/lessons': typeof ManageCoursesCourseIdLessonsRoute
  '/manage/discounts/$discountId/edit': typeof ManageDiscountsDiscountIdEditRoute
  '/manage/events/$eventId/attendees': typeof ManageEventsEventIdAttendeesRoute
  '/manage/events/$eventId/edit': typeof ManageEventsEventIdEditRoute
  '/manage/jobs/$jobId/applicants': typeof ManageJobsJobIdApplicantsRoute
  '/manage/jobs/$jobId/edit': typeof ManageJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/landing': typeof LandingRoute
  '/learn': typeof LearnRoute
  '/my-learning': typeof MyLearningRoute
  '/organization': typeof OrganizationRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/curriculum': typeof CoursesCurriculumRoute
  '/courses/new': typeof CoursesNewRoute
  '/discounts_/$discountId': typeof DiscountsDiscountIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/manage/activity': typeof ManageActivityRoute
  '/manage/bot-logs': typeof ManageBotLogsRoute
  '/manage/faqs': typeof ManageFaqsRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/discounts/': typeof DiscountsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/applications/$applicationId/edit': typeof ApplicationsApplicationIdEditRoute
  '/manage/discounts/$discountId': typeof ManageDiscountsDiscountIdRoute
  '/manage/discounts/new': typeof ManageDiscountsNewRoute
  '/users_/$userId/edit': typeof UsersUserIdEditRoute
  '/manage/courses/': typeof ManageCoursesIndexRoute
  '/manage/discounts/': typeof ManageDiscountsIndexRoute
  '/manage/events/': typeof ManageEventsIndexRoute
  '/manage/jobs/': typeof ManageJobsIndexRoute
  '/manage/courses/$courseId/edit': typeof ManageCoursesCourseIdEditRoute
  '/manage/courses/$courseId/lessons': typeof ManageCoursesCourseIdLessonsRoute
  '/manage/discounts_/$discountId/edit': typeof ManageDiscountsDiscountIdEditRoute
  '/manage/events/$eventId/attendees': typeof ManageEventsEventIdAttendeesRoute
  '/manage/events/$eventId/edit': typeof ManageEventsEventIdEditRoute
  '/manage/jobs/$jobId/applicants': typeof ManageJobsJobIdApplicantsRoute
  '/manage/jobs/$jobId/edit': typeof ManageJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/certificates'
    | '/dashboard'
    | '/donations'
    | '/landing'
    | '/learn'
    | '/my-learning'
    | '/organization'
    | '/verify-certificate'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/courses/$courseId'
    | '/courses/curriculum'
    | '/courses/new'
    | '/discounts/$discountId'
    | '/events/$eventId'
    | '/events/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/manage/activity'
    | '/manage/bot-logs'
    | '/manage/faqs'
    | '/payment/verify'
    | '/settings/organization'
    | '/settings/profile'
    | '/users/$userId'
    | '/applications/'
    | '/courses/'
    | '/discounts/'
    | '/events/'
    | '/jobs/'
    | '/users/'
    | '/applications/$applicationId/edit'
    | '/manage/discounts/$discountId'
    | '/manage/discounts/new'
    | '/users/$userId/edit'
    | '/manage/courses/'
    | '/manage/discounts/'
    | '/manage/events/'
    | '/manage/jobs/'
    | '/manage/courses/$courseId/edit'
    | '/manage/courses/$courseId/lessons'
    | '/manage/discounts/$discountId/edit'
    | '/manage/events/$eventId/attendees'
    | '/manage/events/$eventId/edit'
    | '/manage/jobs/$jobId/applicants'
    | '/manage/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/certificates'
    | '/dashboard'
    | '/donations'
    | '/landing'
    | '/learn'
    | '/my-learning'
    | '/organization'
    | '/verify-certificate'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/courses/$courseId'
    | '/courses/curriculum'
    | '/courses/new'
    | '/discounts/$discountId'
    | '/events/$eventId'
    | '/events/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/manage/activity'
    | '/manage/bot-logs'
    | '/manage/faqs'
    | '/payment/verify'
    | '/settings/organization'
    | '/settings/profile'
    | '/users/$userId'
    | '/applications'
    | '/courses'
    | '/discounts'
    | '/events'
    | '/jobs'
    | '/users'
    | '/applications/$applicationId/edit'
    | '/manage/discounts/$discountId'
    | '/manage/discounts/new'
    | '/users/$userId/edit'
    | '/manage/courses'
    | '/manage/discounts'
    | '/manage/events'
    | '/manage/jobs'
    | '/manage/courses/$courseId/edit'
    | '/manage/courses/$courseId/lessons'
    | '/manage/discounts/$discountId/edit'
    | '/manage/events/$eventId/attendees'
    | '/manage/events/$eventId/edit'
    | '/manage/jobs/$jobId/applicants'
    | '/manage/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/certificates'
    | '/dashboard'
    | '/donations'
    | '/landing'
    | '/learn'
    | '/my-learning'
    | '/organization'
    | '/verify-certificate'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/courses/$courseId'
    | '/courses/curriculum'
    | '/courses/new'
    | '/discounts_/$discountId'
    | '/events/$eventId'
    | '/events/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/manage/activity'
    | '/manage/bot-logs'
    | '/manage/faqs'
    | '/payment/verify'
    | '/settings/organization'
    | '/settings/profile'
    | '/users/$userId'
    | '/applications/'
    | '/courses/'
    | '/discounts/'
    | '/events/'
    | '/jobs/'
    | '/users/'
    | '/applications/$applicationId/edit'
    | '/manage/discounts/$discountId'
    | '/manage/discounts/new'
    | '/users_/$userId/edit'
    | '/manage/courses/'
    | '/manage/discounts/'
    | '/manage/events/'
    | '/manage/jobs/'
    | '/manage/courses/$courseId/edit'
    | '/manage/courses/$courseId/lessons'
    | '/manage/discounts_/$discountId/edit'
    | '/manage/events/$eventId/attendees'
    | '/manage/events/$eventId/edit'
    | '/manage/jobs/$jobId/applicants'
    | '/manage/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CertificatesRoute: typeof CertificatesRoute
  DashboardRoute: typeof DashboardRoute
  DonationsRoute: typeof DonationsRoute
  LandingRoute: typeof LandingRoute
  LearnRoute: typeof LearnRoute
  MyLearningRoute: typeof MyLearningRoute
  OrganizationRoute: typeof OrganizationRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesCurriculumRoute: typeof CoursesCurriculumRoute
  CoursesNewRoute: typeof CoursesNewRoute
  DiscountsDiscountIdRoute: typeof DiscountsDiscountIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsNewRoute: typeof EventsNewRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsNewRoute: typeof JobsNewRoute
  ManageActivityRoute: typeof ManageActivityRoute
  ManageBotLogsRoute: typeof ManageBotLogsRoute
  ManageFaqsRoute: typeof ManageFaqsRoute
  PaymentVerifyRoute: typeof PaymentVerifyRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DiscountsIndexRoute: typeof DiscountsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApplicationsApplicationIdEditRoute: typeof ApplicationsApplicationIdEditRoute
  ManageDiscountsDiscountIdRoute: typeof ManageDiscountsDiscountIdRoute
  ManageDiscountsNewRoute: typeof ManageDiscountsNewRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
  ManageCoursesIndexRoute: typeof ManageCoursesIndexRoute
  ManageDiscountsIndexRoute: typeof ManageDiscountsIndexRoute
  ManageEventsIndexRoute: typeof ManageEventsIndexRoute
  ManageJobsIndexRoute: typeof ManageJobsIndexRoute
  ManageCoursesCourseIdEditRoute: typeof ManageCoursesCourseIdEditRoute
  ManageCoursesCourseIdLessonsRoute: typeof ManageCoursesCourseIdLessonsRoute
  ManageDiscountsDiscountIdEditRoute: typeof ManageDiscountsDiscountIdEditRoute
  ManageEventsEventIdAttendeesRoute: typeof ManageEventsEventIdAttendeesRoute
  ManageEventsEventIdEditRoute: typeof ManageEventsEventIdEditRoute
  ManageJobsJobIdApplicantsRoute: typeof ManageJobsJobIdApplicantsRoute
  ManageJobsJobIdEditRoute: typeof ManageJobsJobIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/curriculum': {
      id: '/courses/curriculum'
      path: '/courses/curriculum'
      fullPath: '/courses/curriculum'
      preLoaderRoute: typeof CoursesCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/new': {
      id: '/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof CoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts/': {
      id: '/discounts/'
      path: '/discounts'
      fullPath: '/discounts/'
      preLoaderRoute: typeof DiscountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts_/$discountId': {
      id: '/discounts_/$discountId'
      path: '/discounts/$discountId'
      fullPath: '/discounts/$discountId'
      preLoaderRoute: typeof DiscountsDiscountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/activity': {
      id: '/manage/activity'
      path: '/manage/activity'
      fullPath: '/manage/activity'
      preLoaderRoute: typeof ManageActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/bot-logs': {
      id: '/manage/bot-logs'
      path: '/manage/bot-logs'
      fullPath: '/manage/bot-logs'
      preLoaderRoute: typeof ManageBotLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/faqs': {
      id: '/manage/faqs'
      path: '/manage/faqs'
      fullPath: '/manage/faqs'
      preLoaderRoute: typeof ManageFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/verify': {
      id: '/payment/verify'
      path: '/payment/verify'
      fullPath: '/payment/verify'
      preLoaderRoute: typeof PaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/edit': {
      id: '/applications/$applicationId/edit'
      path: '/applications/$applicationId/edit'
      fullPath: '/applications/$applicationId/edit'
      preLoaderRoute: typeof ApplicationsApplicationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/courses/': {
      id: '/manage/courses/'
      path: '/manage/courses'
      fullPath: '/manage/courses/'
      preLoaderRoute: typeof ManageCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/discounts/': {
      id: '/manage/discounts/'
      path: '/manage/discounts'
      fullPath: '/manage/discounts/'
      preLoaderRoute: typeof ManageDiscountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/discounts/$discountId': {
      id: '/manage/discounts/$discountId'
      path: '/manage/discounts/$discountId'
      fullPath: '/manage/discounts/$discountId'
      preLoaderRoute: typeof ManageDiscountsDiscountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/discounts/new': {
      id: '/manage/discounts/new'
      path: '/manage/discounts/new'
      fullPath: '/manage/discounts/new'
      preLoaderRoute: typeof ManageDiscountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/events/': {
      id: '/manage/events/'
      path: '/manage/events'
      fullPath: '/manage/events/'
      preLoaderRoute: typeof ManageEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/jobs/': {
      id: '/manage/jobs/'
      path: '/manage/jobs'
      fullPath: '/manage/jobs/'
      preLoaderRoute: typeof ManageJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$userId/edit': {
      id: '/users_/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/courses/$courseId/edit': {
      id: '/manage/courses/$courseId/edit'
      path: '/manage/courses/$courseId/edit'
      fullPath: '/manage/courses/$courseId/edit'
      preLoaderRoute: typeof ManageCoursesCourseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/courses/$courseId/lessons': {
      id: '/manage/courses/$courseId/lessons'
      path: '/manage/courses/$courseId/lessons'
      fullPath: '/manage/courses/$courseId/lessons'
      preLoaderRoute: typeof ManageCoursesCourseIdLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/discounts_/$discountId/edit': {
      id: '/manage/discounts_/$discountId/edit'
      path: '/manage/discounts/$discountId/edit'
      fullPath: '/manage/discounts/$discountId/edit'
      preLoaderRoute: typeof ManageDiscountsDiscountIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/events/$eventId/attendees': {
      id: '/manage/events/$eventId/attendees'
      path: '/manage/events/$eventId/attendees'
      fullPath: '/manage/events/$eventId/attendees'
      preLoaderRoute: typeof ManageEventsEventIdAttendeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/events/$eventId/edit': {
      id: '/manage/events/$eventId/edit'
      path: '/manage/events/$eventId/edit'
      fullPath: '/manage/events/$eventId/edit'
      preLoaderRoute: typeof ManageEventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/jobs/$jobId/applicants': {
      id: '/manage/jobs/$jobId/applicants'
      path: '/manage/jobs/$jobId/applicants'
      fullPath: '/manage/jobs/$jobId/applicants'
      preLoaderRoute: typeof ManageJobsJobIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/jobs/$jobId/edit': {
      id: '/manage/jobs/$jobId/edit'
      path: '/manage/jobs/$jobId/edit'
      fullPath: '/manage/jobs/$jobId/edit'
      preLoaderRoute: typeof ManageJobsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CertificatesRoute: CertificatesRoute,
  DashboardRoute: DashboardRoute,
  DonationsRoute: DonationsRoute,
  LandingRoute: LandingRoute,
  LearnRoute: LearnRoute,
  MyLearningRoute: MyLearningRoute,
  OrganizationRoute: OrganizationRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesCurriculumRoute: CoursesCurriculumRoute,
  CoursesNewRoute: CoursesNewRoute,
  DiscountsDiscountIdRoute: DiscountsDiscountIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsNewRoute: EventsNewRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsNewRoute: JobsNewRoute,
  ManageActivityRoute: ManageActivityRoute,
  ManageBotLogsRoute: ManageBotLogsRoute,
  ManageFaqsRoute: ManageFaqsRoute,
  PaymentVerifyRoute: PaymentVerifyRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DiscountsIndexRoute: DiscountsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApplicationsApplicationIdEditRoute: ApplicationsApplicationIdEditRoute,
  ManageDiscountsDiscountIdRoute: ManageDiscountsDiscountIdRoute,
  ManageDiscountsNewRoute: ManageDiscountsNewRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
  ManageCoursesIndexRoute: ManageCoursesIndexRoute,
  ManageDiscountsIndexRoute: ManageDiscountsIndexRoute,
  ManageEventsIndexRoute: ManageEventsIndexRoute,
  ManageJobsIndexRoute: ManageJobsIndexRoute,
  ManageCoursesCourseIdEditRoute: ManageCoursesCourseIdEditRoute,
  ManageCoursesCourseIdLessonsRoute: ManageCoursesCourseIdLessonsRoute,
  ManageDiscountsDiscountIdEditRoute: ManageDiscountsDiscountIdEditRoute,
  ManageEventsEventIdAttendeesRoute: ManageEventsEventIdAttendeesRoute,
  ManageEventsEventIdEditRoute: ManageEventsEventIdEditRoute,
  ManageJobsJobIdApplicantsRoute: ManageJobsJobIdApplicantsRoute,
  ManageJobsJobIdEditRoute: ManageJobsJobIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
